// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKZc2T11YF3GfA26ARrs9eGCoze4m9jY',
    appId: '1:612943729936:web:3dfdc46c17920d420c0195',
    messagingSenderId: '612943729936',
    projectId: 'runrank-8171e',
    authDomain: 'runrank-8171e.firebaseapp.com',
    storageBucket: 'runrank-8171e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1GD4zxHpMu1pfj3o-_dbdiX6yIIvLM8s',
    appId: '1:612943729936:android:f70b9f0e60a868a70c0195',
    messagingSenderId: '612943729936',
    projectId: 'runrank-8171e',
    storageBucket: 'runrank-8171e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZC6Z_fSzK_8-5BJ40PX-t9E4SXL697E',
    appId: '1:612943729936:ios:0105e3bb476bed8a0c0195',
    messagingSenderId: '612943729936',
    projectId: 'runrank-8171e',
    storageBucket: 'runrank-8171e.firebasestorage.app',
    iosBundleId: 'com.example.runrank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPZC6Z_fSzK_8-5BJ40PX-t9E4SXL697E',
    appId: '1:612943729936:ios:0105e3bb476bed8a0c0195',
    messagingSenderId: '612943729936',
    projectId: 'runrank-8171e',
    storageBucket: 'runrank-8171e.firebasestorage.app',
    iosBundleId: 'com.example.runrank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKZc2T11YF3GfA26ARrs9eGCoze4m9jY',
    appId: '1:612943729936:web:fc060fe08cc7fe980c0195',
    messagingSenderId: '612943729936',
    projectId: 'runrank-8171e',
    authDomain: 'runrank-8171e.firebaseapp.com',
    storageBucket: 'runrank-8171e.firebasestorage.app',
  );
}
